### ISSUE TITLE
Beep setting

### ISSUE THREAD

**Issue by marcodipasqua** [oyvindwe/connectlife#13]
Hi,

I disabled the beep on the ConnectLife app and it perfectly works: there is no beep from my air conditioner when I change the setpoint or other. But when I change a parameter using the connectlife-ha integration, the AC beeps. Can a setting be added?

BWT, in [Connectlife API proxy / MQTT Home Assistant integration](https://github.com/bilan/connectlife-api-connector), there is a "beep" option in the add-on configuration and it perfectly works.

**Comment by oyvindwe** [comment]
Ah, it seems that `t_beep: 0` must be included in all the requests to avoid this. I think it makes sense to add that as an option to the `Climate` entity - I'll look into it!

**Comment by oyvindwe** [comment]
By the way, this issue belongs in the HA integration repo: https://github.com/oyvindwe/connectlife-ha

**Comment by marcodipasqua** [comment]
I got it, should I move this?

**Comment by oyvindwe** [comment]
Not necessary, I have a PR ready soon. I'm closing this issue though.

**Comment by oyvindwe** [comment]
Btw - fixed in [connectlife-ha version 0.12.0](https://github.com/oyvindwe/connectlife-ha/releases/tag/v0.12.0)

**Comment by marcodipasqua** [comment]
It works like a charm!
Thanks :)
